### ISSUE TITLE
How about using right mouse button to scroll the content? Is it necessary?

### ISSUE THREAD

**Issue by eynol** [Jianru-Lin/fmtjs-web#1]
**It's very uncomfortable to move mouse between content and browser's scroll bar when I expand all code.** Although a touchpad or a touchable device (like iPad) may help this, mouse is still a helpful device for users to interact with computer.

The left mouse button is used to click code blocks. It's the first choice to scroll the content when it's pressed and moved. However, it may causing confusion, which is "select text or scroll content?". 
The middle mouse button has it's default behaviors, but it scrolls too fast. 

There is another choice, but it's may tire your finger and arm. When you want to use right mouse to scroll content, just press Ctrl key or Meta key before you move your mouse. 

Is it necessary to use right mouse to scroll the content?

**Comment by Jianru-Lin** [comment]
@vankai Thanks for your suggestion. 😄 Did you mean *drag to move* by right mouse button?

**Comment by eynol** [comment]
@Jianru-Lin Yes, it is. :joy_cat:  Will it be supported in future?

**Comment by Jianru-Lin** [comment]
@vankai How about install some chrome/firefox extensions to achieve it? 

http://lifehacker.com/287342/add-drag-scrolling-and-momentum-flicking-with-grab-and-drag

**Comment by eynol** [comment]
@Jianru-Lin  Maybe a good solution.
